### ISSUE TITLE
Correctness Problems running vanilla repo

### ISSUE THREAD

**Issue by georghinkel** [ATL-Research/incremental-class2relational#24]
I get the following output sequence running check_solution.sh without any changes in the repository:

```
atl,correctness10,correctness,error
atl,correctness11,correctness,error
atl,correctness12,correctness,ok
atl,correctness13,correctness,error
atl,correctness2,correctness,error
atl,correctness3,correctness,error
atl,correctness4,correctness,error
atl,correctness5,correctness,error
atl,correctness6,correctness,error
atl,correctness7,correctness,error
atl,correctness8,correctness,error
atl,correctness9,correctness,ok
atl,correctness_couple,correctness,ok
atl,correctness_full,correctness,error
atl,scale1,correctness,error
atl,scale200,correctness,ok
atl,scale2000,correctness,ok
atol,correctness1,correctness,ok
atol,correctness10,correctness,ok
atol,correctness11,correctness,ok
atol,correctness12,correctness,ok
atol,correctness13,correctness,error
atol,correctness2,correctness,ok
atol,correctness3,correctness,ok
atol,correctness4,correctness,ok
atol,correctness5,correctness,ok
atol,correctness6,correctness,ok
atol,correctness7,correctness,ok
atol,correctness8,correctness,error
atol,correctness9,correctness,ok
atol,correctness_couple,correctness,ok
atol,correctness_full,correctness,error
atol,scale1,correctness,ok
atol,scale200,correctness,ok
atol,scale2000,correctness,ok
java,correctness1,correctness,error
java,correctness10,correctness,error
java,correctness11,correctness,error
java,correctness12,correctness,error
```

(Afterwards, I aborted execution due to lack of time).

Is it normal that in the current form, most tools fail most correctness tests or do I have a problem on my machine? In the latter case, what could be causing this?

I also noticed several uncaught exceptions.

I was executing the test script on Ubuntu 22.04 in WSL / Windows 10. JDK version is 17.0.6.

**Comment by TheoLeCalvar** [comment]
Correctness test report is a bit confusing right now. To be correct a transformation should produce the same result when :
1) applying transformation then changes
2) applying change then transformation

For ATL, it is normal that is reports errors for most scenario because the transformation is not incremental. Thus it does nothing with the changes. The only scenario passing are the one that produce identical models (such as adding & removing the same element, applying no change at all, ...).


For ATOL, we have some issues that we need to fix in specific scenario.

@goetzst  can comment on the Java solution.



Uncaught exception are acceptable results as described in the case paper especially since some of these change test for corner cases (add null value, removing relations, ...).
For instance, crashing on a accessing a null value is the default ATL behavior (listed as behavior (1) in the case description).

**Comment by goetzst** [comment]
There is currently still a bug in the java solution that makes it misbehave for some changes. We're working on fixing that as soon as possible. So for now I expect the reported errors for Java to be due to that and not because of something on your end.
